import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Szyfrowanie {
    private JPanel pMain;
    private JTextField textSzyfr;
    private JTextArea textAreaSzyfr;
    private JButton btnSZyfr;
    private JTextArea textAreaSzyfrowanie;
    private JButton zapiszDoPlikuButton;
    private JLabel wpiszSzyfrLabel;
    private JLabel twójZaszyfrowanyTekstLabel;
    private JLabel wpiszTekstLabel;


    public Szyfrowanie() {
        btnSZyfr.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String kluczWartosc = textSzyfr.getText();
                int kluczLiczba = Integer.parseInt(kluczWartosc);
                String text = textAreaSzyfr.getText();
                String ukryty = SzyfrCezara.szyfruj(kluczLiczba, text);
                textAreaSzyfrowanie.setText(ukryty);
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Szyfrowanie");
        frame.setContentPane(new Szyfrowanie().pMain);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pMain = new JPanel();
        pMain.setLayout(new GridLayoutManager(6, 5, new Insets(5, 15, 10, 15), -1, -1));
        pMain.setBackground(new Color(-5991578));
        pMain.setForeground(new Color(-16777216));
        pMain.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), "Szyfrowanie", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        wpiszTekstLabel = new JLabel();
        wpiszTekstLabel.setForeground(new Color(-16777216));
        wpiszTekstLabel.setHorizontalAlignment(10);
        wpiszTekstLabel.setHorizontalTextPosition(10);
        wpiszTekstLabel.setText("Wpisz tekst");
        pMain.add(wpiszTekstLabel, new GridConstraints(3, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, new Dimension(100, 16), new Dimension(150, 36), null, 1, false));
        textSzyfr = new JTextField();
        textSzyfr.setBackground(new Color(-2763871));
        textSzyfr.setForeground(new Color(-16777216));
        textSzyfr.setHorizontalAlignment(2);
        pMain.add(textSzyfr, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, 1, null, new Dimension(150, 34), new Dimension(150, -1), 0, false));
        wpiszSzyfrLabel = new JLabel();
        wpiszSzyfrLabel.setForeground(new Color(-16777216));
        wpiszSzyfrLabel.setText("Wpisz szyfr");
        pMain.add(wpiszSzyfrLabel, new GridConstraints(1, 0, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_VERTICAL, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, 17), new Dimension(160, 36), 0, false));
        btnSZyfr = new JButton();
        btnSZyfr.setHorizontalAlignment(0);
        btnSZyfr.setHorizontalTextPosition(0);
        btnSZyfr.setText("Szyfruj");
        pMain.add(btnSZyfr, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        zapiszDoPlikuButton = new JButton();
        zapiszDoPlikuButton.setText("Zapisz do pliku");
        pMain.add(zapiszDoPlikuButton, new GridConstraints(5, 4, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(192, 34), null, 0, false));
        textAreaSzyfrowanie = new JTextArea();
        textAreaSzyfrowanie.setBackground(new Color(-2763871));
        textAreaSzyfrowanie.setEditable(false);
        textAreaSzyfrowanie.setForeground(new Color(-16777216));
        textAreaSzyfrowanie.setLineWrap(true);
        pMain.add(textAreaSzyfrowanie, new GridConstraints(4, 4, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(100, 100), new Dimension(192, 201), null, 0, false));
        textAreaSzyfr = new JTextArea();
        textAreaSzyfr.setBackground(new Color(-2763871));
        textAreaSzyfr.setForeground(new Color(-16777216));
        textAreaSzyfr.setLineWrap(true);
        pMain.add(textAreaSzyfr, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, new Dimension(100, 100), new Dimension(200, 200), null, 0, false));
        twójZaszyfrowanyTekstLabel = new JLabel();
        twójZaszyfrowanyTekstLabel.setForeground(new Color(-16777216));
        twójZaszyfrowanyTekstLabel.setText("Twój zaszyfrowany tekst");
        pMain.add(twójZaszyfrowanyTekstLabel, new GridConstraints(3, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pMain.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        wpiszTekstLabel.setLabelFor(textAreaSzyfr);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pMain;
    }

}
